### ISSUE TITLE
How to disable spontaneous prefix generation?

### ISSUE THREAD

**Issue by dtaht** [sbyx/hnetd#21]
My topology:

8 port rangely router, ubuntu 14.10, running hnetd --ulaprefix=fd03::/48

various boxes on various ports. 1 nuc connected to a beaglebone over usb. Everything running ubuntu.

problem A) hnet-ifup eth0 eth1 eth2 eth3 only takes the first arg. Running it separately gets a very different /64 for each interface (but yea! I get addresses)

problem B) I bring up hnetd on the nuc, and it does a spontaneous prefix generation, where basically I want it to be a slave and/or relay (bringing up addresses/prefixes on eth0 and eth1 (usb) or not depending on whether I decide to run hnet-ifup on those, and just letting the beaglebone (which is running a version of debian that doesnt have the json apt at all ). But it goes and  creates a prefix I dont want and distributes that...

Coolness was that the rangely picked up the new ula and distributed it to all devices, and when I killed that hnetd on the nuc, they did expire and get removed eventually. 

I will hopefully figure this out shortly, but it looks to me as though this code path always gets executed...

**Comment by dtaht** [comment]
I am still hoping for a way to distribute a /61 instead of 8 /64s in this case

**Comment by dtaht** [comment]
and while I am kvetching - doing wakeups for any reason other than I/O or a protocol timeout wastes power on (particularly battery operated) devices.

**Comment by fingon** [comment]
You could give hints to give similar /64s to particular end node, and then RP should (in theory) notice aggregation. Good luck with that in practise though.

**Comment by fingon** [comment]
disable_pa option has been around for awhile now actually. Never just tested, and it seems to have some issues if changing the value 'on the fly' without restarting hnetd, but I am closing this as done.
