### ISSUE TITLE
relay only mode?

### ISSUE THREAD

**Issue by dtaht** [sbyx/hnetd#25]
I would like to be able to at least get hnetd built and deployed along the middle backbone
of my network. I have very little desire to hand it control of address assignment on the 
interveining hops, and in fact, the middle hops don't need any ipv6 addresses on them at all.

Basic topology:

gw - router - router - router - router - ap

Is there a way to configure hnetd to act as a relay for each "router" here?

**Comment by fingon** [comment]
disable_pa 1 per-interface. Seems to work based on some testing (although has issue if you change it dynamically, but that's different.)
