### ISSUE TITLE
libubox depends on lua

### ISSUE THREAD

**Issue by Abhayakara** [sbyx/hnetd#30]
Is there a need to pull lua in in order for hnetd to work, or is this just by happenstance?

**Comment by fingon** [comment]
cmake -DBUILD_LUA=OFF . (for 'live' Debian binary building Makefile example, see https://github.com/fingon/hnet/blob/master/component/Makefile )

**Comment by Abhayakara** [comment]
Great, thanks.   I figured out how to turn it off with -i, but haven't gotten past that to building hnetd yet. :)
