### ISSUE TITLE
json library dependency is not captured by cmake.

### ISSUE THREAD

**Issue by Abhayakara** [sbyx/hnetd#31]
cmake ran happily and made makefiles, but the make craps out thusly:

Scanning dependencies of target hnetd
[ 47%] Building C object CMakeFiles/hnetd.dir/src/hncp_routing.c.o
[ 50%] Building C object CMakeFiles/hnetd.dir/src/hncp_dump.c.o
In file included from /home/mellon/hnetd/src/hncp_dump.c:5:0:
/usr/include/libubox/blobmsg_json.h:22:24: fatal error: json/json.h: No such file or directory
  #include <json/json.h>

I assume it's looking for a json library; if so, cmake needs to check for it.

**Comment by fingon** [comment]
I guess you are having fun, but there _is_ https://github.com/sbyx/hnetd/blob/master/build-generic.sh because someone told us this is too hard to build :) (disclaimer: probably works at least with recent Debian and Ubuntu, but for 'something else' may also be useful advice)

**Comment by Abhayakara** [comment]
On Apr 9, 2015, at 11:53 AM, Markus Stenberg <notifications@github.com> wrote:
> I guess you are having fun, but there is https://github.com/sbyx/hnetd/blob/master/build-generic.sh because someone told us this is too hard to build :) (disclaimer: probably works at least with recent Debian and Ubuntu, but for 'something else' may also be useful advice)

Hm, OK, I guess.   But the cmake config still ought to detect the dependencies!   :)

**Comment by sbyx** [comment]
Thanks for the hint. I added the necessary checks in https://github.com/sbyx/hnetd/commit/187ce05ea8e44bd5c16e1a6141b46a7f398e701e
will merge this into master soon.

**Comment by Abhayakara** [comment]
On Apr 9, 2015, at 1:39 PM, Steven Barth <notifications@github.com> wrote:
> Thanks for the hint. I added the necessary checks in 187ce05
> will merge this into master soon.

Great, thanks!

**Comment by fingon** [comment]
It is in master now; closing.
