### ISSUE TITLE
In v4, half of addresses are used, not quarter

### ISSUE THREAD

**Issue by fingon** [sbyx/hnetd#34]
hncp_pa.c:252 says 'use first quarter of available addresses', but it is not obvious how it does it; in practise it seems to use at least half of them in v4 case.. (I have case where .112 is assigned both to a router and to client via DHCP - ouch).

**Comment by Oryon** [comment]
dc6f333aa13a58fa58a48216ea64412357765190 adds the feature to PA and hncp_pa uses it.
