### ISSUE TITLE
.0 is reserved address in V4, and in Linux prefix:: address does not work

### ISSUE THREAD

**Issue by fingon** [sbyx/hnetd#35]
=> please start AA at 1 :)

**Comment by fingon** [comment]
(prefix:: address is 'subnet device anycast' according to Cisco IOS documentation, so it is a bad idea.)

**Comment by Oryon** [comment]
d3fdc841271370578ebd410d8fefb5f00d4e4b2d and f76f309df08e82244a1a7cbcf0d612f728be7404 should fix that.
