### ISSUE TITLE
HNCP lifetimes use wrong format

### ISSUE THREAD

**Issue by fingon** [sbyx/hnetd#46]
They are specified as seconds in e.g. DHCP{v4,v6} _and_ current HNCP text. However, code seems to assume they are milliseconds and hilarity may ensue due to that if someone actually implements HNCP correctly.. :)

**Comment by Oryon** [comment]
14a4c8643181992c7e69ea0ca6ae91810d5dc3ee should fix it.

**Comment by sbyx** [comment]
wrong issue ;)

**Comment by fingon** [comment]
Probably makes sense to do this with the HNCP-09 enhancements (they break compatibility anyway); we'll have eventual port#/multicast-group based incompatibility coming too at some point, perhaps.

**Comment by fingon** [comment]
Fixed in 94f6010517b539aa32703b9ea47015418d06b83e.
