### ISSUE TITLE
Cannot set upstream dhcpv4 options for authentication with ISP

### ISSUE THREAD

**Issue by timcoote** [sbyx/hnetd#61]
My ISP (Sky, UK), uses dhcpv4 options 60 and 61 as part of its authentication and configuration management (it uses ClientId to authenticate the endpoint and the Vendor Class value to identify the firmware version).

I've not managed to find how to set these parameters for hnetd. 

Even if I hard-code suitable values in hnetd/src/platform-openwrt.c's handle_restart_dhcp, there are duplicate Vendor Class parameters as udhcpc adds its own.

It's likely that I'm taking the wrong approach, but if not, I'm happy to lobby udhcpc to fix what looks like a known issue. 

With a bit of support, I could even create a patch to set the parameters.

**Comment by fingon** [comment]
the 'hnet' proto supports setting client id already (see openwrt/hnet.sh - dhcpv4_clientid and dhcpv6_clientid options ) ; it basically just sets parameters to the underlying dhcp proto. I am not sure if underlying dhcp proto supports setting vendor class, but if it does, you could add that similarly.

Otherwise you could just edit the dhcp proto handler by hand (it is a shell script, which invokes udhcpc).

**Comment by timcoote** [comment]
I couldn't see how the dhcp protocol handler was invoked by hnet. I did find a note to the effect that mixing dhcp and hnet on the same interface in /etc/config/network could cause a mess, so I assumed that it wasn't

**Comment by fingon** [comment]
src/platform-openwrt.c / handle_restart_dhcp creates dynamic sub-interface with hnet proto for the interface, and passes along that clientid _for ipv6_. ipv4 for some reason seems not to be handled :-p 

The option 0x4d it sets up in the sendopts is the 'homenet' text for dhcp. Something similar could be done with client/vendor id.

(Apparently DHCPv4 client id code is partially done, and hnet.sh does not pass it along - DHCPv6 does seem to work. )

**Comment by timcoote** [comment]
lol. I've just about managed to reverse engineer some of that, although it's not at all clear to me how to find out how the various bits fit together. 0x4d is even more weird in that it's a length/string structure. Presumably the other types are delimited some other way. I'll see if I can code up the parameters directly into the dhcp.sh

**Comment by timcoote** [comment]
fwiw, the fact that udhcpc handles some parameters by name (e.g. clientid, vendorclass) but does not check that the relevant parameters have been passed in sendopts seems to create the confusion. Also, I seemed to get different behaviour depending on the order in which I encoded the parameters as space separated key:value pairs :-(

**Comment by timcoote** [comment]
Suggestion works. Thanks, I can now reproduce the tcpdump from my sky box using openwrt.

**Comment by timcoote** [comment]
fwiw, the dhcpv4_clientid didn’t work for me. could be finger trouble as it’s v. hard to work out what’s supposed to happen.
